import Mathlib

/-!
# Sealed49.Defs

Definitions mirroring `data/sealed-49/statement.md` (the pinned statement of
record for run SEALED49), plus `M_c`/`H_c` from `candidate-proof.md` Part 0
(shared vocabulary for the orbit characterization, Part 0). Every definition
below cites the exact statement.md line(s) or candidate-proof.md Part it
mirrors.

Ambient convention: `[m] = {0,...,m-1}` (statement.md line 6) is `Fin m`
throughout. A "2-coloring of the edges of `K_n`" is represented by a single
`G : SimpleGraph (Fin n)` playing the role of "the color-1 graph"; "color 2"
is then `Gᶜ` (`SimpleGraph` complement: `Gᶜ.Adj x y ↔ x ≠ y ∧ ¬ G.Adj x y`),
matching candidate-proof.md's own usage ("let `G` be the color-1 graph").
-/

namespace Sealed49

open scoped Classical
noncomputable section

/-- statement.md lines 9-10: the alternating sequence value at position `i`
(0-indexed) for a graph on `[a]`: `s_{2t} = t`, `s_{2t+1} = a-1-t`. -/
def altSeqVal (a i : ℕ) : ℕ :=
  if i % 2 = 0 then i / 2 else a - 1 - i / 2

/-- statement.md lines 9-11: `P_a^alt`, the graph on `[a]` whose `a-1` edges
are the consecutive pairs `{s_i, s_{i+1}}` of the sequence `altSeqVal a`. -/
def Palt (a : ℕ) : SimpleGraph (Fin a) :=
  SimpleGraph.fromRel (fun x y : Fin a =>
    ∃ i : ℕ, i + 1 < a ∧ x.val = altSeqVal a i ∧ y.val = altSeqVal a (i + 1))

/-- statement.md line 15: `ρ(i) = i+1 (mod m)`, `Dih(m)`'s rotation
generator. Mathlib's `finRotate m : Equiv.Perm (Fin m)` satisfies
`finRotate m i = i + 1` (`Fin m`'s own `+`, i.e. addition mod `m`). -/
def rhoPerm (m : ℕ) : Equiv.Perm (Fin m) := finRotate m

/-- statement.md line 15: `σ(i) = m-1-i`, `Dih(m)`'s reflection generator.
Mathlib's `Fin.revPerm : Equiv.Perm (Fin m)` is exactly `i ↦ m-1-i`. -/
def sigmaPerm (m : ℕ) : Equiv.Perm (Fin m) := Fin.revPerm

/-- statement.md line 14: `Dih(m) ≤ Sym([m])`, generated by `ρ`, `σ`. -/
def Dih (m : ℕ) : Subgroup (Equiv.Perm (Fin m)) :=
  Subgroup.closure {rhoPerm m, sigmaPerm m}

/-- The graph obtained from `H` (on `[a]`) by relabeling via `γ`: edge set
`{{γ(i),γ(j)} : {i,j} ∈ E(H)}` (statement.md line 22). Realized as pulling
`H`'s adjacency back along `γ⁻¹`, so `(actGraph γ H).Adj (γ i) (γ j) ↔
H.Adj i j` (`γ.symm (γ i) = i`). -/
def actGraph {a : ℕ} (γ : Equiv.Perm (Fin a)) (H : SimpleGraph (Fin a)) : SimpleGraph (Fin a) :=
  H.comap γ.symm

/-- candidate-proof.md Lemma 3.1's "mirror": relabel a graph on `[q]` by
`i ↦ (q-1)-i`. -/
def mirrorGraph (q : ℕ) (K : SimpleGraph (Fin q)) : SimpleGraph (Fin q) :=
  actGraph Fin.revPerm K

/-- candidate-proof.md Part 0 (line 23): `M_c = {{i,j} ⊆ [a] : i≠j, i+j≡c
(mod a)}`, for `c` ranging over `Z/aZ`. -/
def Mgraph (a : ℕ) (c : ZMod a) : SimpleGraph (Fin a) :=
  SimpleGraph.fromRel (fun x y : Fin a => (x.val : ZMod a) + (y.val : ZMod a) = c)

/-- candidate-proof.md Part 0 (line 24): `H_c = M_c ∪ M_{c+1}`. -/
def Hgraph (a : ℕ) (c : ZMod a) : SimpleGraph (Fin a) :=
  Mgraph a c ⊔ Mgraph a (c + 1)

/-- statement.md lines 17-24: a `Γ`-copy of `H` (graph on `[m]`) in the
"color" represented by `target`: an increasing map `v : [m] ↪o [n]` together
with `γ ∈ Γ` such that every edge `{i,j}` of `H` maps to a `target`-edge
`{v(γ(i)), v(γ(j))}`. -/
def GammaCopy {m n : ℕ} (H : SimpleGraph (Fin m)) (Γ : Subgroup (Equiv.Perm (Fin m)))
    (target : SimpleGraph (Fin n)) : Prop :=
  ∃ (v : Fin m ↪o Fin n) (γ : Equiv.Perm (Fin m)), γ ∈ Γ ∧
    ∀ i j : Fin m, H.Adj i j → target.Adj (v (γ i)) (v (γ j))

/-- statement.md lines 26-31: `R_dih(H1,H2)`, the least `n` such that every
2-coloring of `K_n` (represented by `G`, color 1) contains a `Dih(m1)`-copy
of `H1` in color 1 or a `Dih(m2)`-copy of `H2` in color 2 (i.e. in `Gᶜ`). -/
def Rdih {m1 m2 : ℕ} (H1 : SimpleGraph (Fin m1)) (H2 : SimpleGraph (Fin m2)) : ℕ :=
  sInf {n : ℕ | ∀ G : SimpleGraph (Fin n), GammaCopy H1 (Dih m1) G ∨ GammaCopy H2 (Dih m2) Gᶜ}

/-- statement.md line 29: `K_b`, the complete graph on `[b]`. -/
def Kgraph (b : ℕ) : SimpleGraph (Fin b) := ⊤

/-- candidate-proof.md Parts 3-4: an increasing tuple `v` "realizes" `H` in
the ambient graph `G` when every `H`-edge maps to a `G`-edge (no group
action here; `v` alone does the relabeling). Used throughout Parts 3-4 for
"increasing tuple ... realizing `P_p^alt`" / "realizing `H_c`". -/
def Realizes {p n : ℕ} (H : SimpleGraph (Fin p)) (G : SimpleGraph (Fin n))
    (v : Fin p ↪o Fin n) : Prop :=
  ∀ i j : Fin p, H.Adj i j → G.Adj (v i) (v j)

/-- Degree of `m` in `G`, counting only neighbors lying in `W` ("`G`
restricted to `W`", the Part 2/4/5/6 ambient-set convention). -/
def degreeOn {n : ℕ} (G : SimpleGraph (Fin n)) (W : Finset (Fin n)) (m : Fin n) : ℕ :=
  (W.filter (fun w => G.Adj w m)).card

/-- Minimum degree of `G` restricted to `W` (`δ(G)` on `W`; `0` if `W` is
empty). -/
def minDegreeOn {n : ℕ} (G : SimpleGraph (Fin n)) (W : Finset (Fin n)) : ℕ :=
  if h : W.Nonempty then W.inf' h (degreeOn G W) else 0

end
end Sealed49
