"""Independent check of Lemma 0.2 (orbit/stabilizer of P_a^alt under Dih(a)).

Built ONLY from statement.md's definitions (sequence for P_a^alt, generators
rho/sigma of Dih(a)) -- NOT from the proof's H_c/M_c reindexing machinery.
Also checks statement.md's own "sanity anchor" (orbit size == a for 3<=a<=14).
"""
from itertools import product


def p_alt_edges(a):
    """P_a^alt: edges = consecutive pairs of (0,a-1,1,a-2,2,...)."""
    seq = []
    for t in range((a + 1) // 2):
        seq.append(t)
        if len(seq) < a:
            seq.append(a - 1 - t)
    seq = seq[:a]
    edges = set()
    for i in range(a - 1):
        edges.add(frozenset((seq[i], seq[i + 1])))
    assert len(edges) == a - 1, (a, seq, edges)
    return frozenset(edges), seq


def dih_group(a):
    """Dih(a) as the set of permutations (tuples) generated by rho,sigma,
    obtained by closure (BFS) so no assumption about group structure is
    baked in beyond the two generators in statement.md."""
    def rho(perm):
        return tuple((perm[i] + 1) % a for i in range(a))  # not used directly

    rho0 = tuple((i + 1) % a for i in range(a))
    sigma0 = tuple((a - 1 - i) % a for i in range(a))

    def compose(f, g):
        # (f after g): apply g then f, both given as images-of-i tuples
        return tuple(f[g[i]] for i in range(a))

    ident = tuple(range(a))
    seen = {ident}
    frontier = [ident]
    gens = [rho0, sigma0]
    while frontier:
        new_frontier = []
        for perm in frontier:
            for g in gens:
                np_ = compose(g, perm)
                if np_ not in seen:
                    seen.add(np_)
                    new_frontier.append(np_)
        frontier = new_frontier
    return seen


def apply_perm(perm, edges):
    return frozenset(frozenset((perm[i], perm[j])) for (i, j) in
                      (tuple(e) for e in edges))


def check(a):
    edges, seq = p_alt_edges(a)
    G = dih_group(a)
    assert len(G) == 2 * a, (a, len(G))
    orbit = set()
    stab = 0
    for perm in G:
        img = apply_perm(perm, edges)
        orbit.add(img)
        if img == edges:
            stab += 1
    ok_orbit_stab = len(orbit) * stab == len(G)
    return {
        "a": a,
        "parity": "even" if a % 2 == 0 else "odd",
        "orbit_size": len(orbit),
        "stab_size": stab,
        "group_size": len(G),
        "orbit_times_stab_eq_group": ok_orbit_stab,
        "orbit_size_eq_a": len(orbit) == a,
        "stab_size_eq_2": stab == 2,
    }


if __name__ == "__main__":
    results = [check(a) for a in range(3, 15)]  # statement.md anchor range
    extra = [check(a) for a in (16, 17, 20, 21)]  # a bit beyond, both parities
    all_results = results + extra
    all_ok = all(
        r["orbit_size_eq_a"] and r["stab_size_eq_2"] and r["orbit_times_stab_eq_group"]
        for r in all_results
    )
    for r in all_results:
        print(r)
    print("ALL_OK:", all_ok)
