"""
Independent implementation of the objects pinned in statement.md.
Built ONLY from the definitions in statement.md -- does not import or
consult candidate-proof.md's own constructions (H_c, mirror, P(m)/Q(m)).
Used as ground truth for cross-checking the proof.
"""
from itertools import combinations, permutations


def palt_edges(a):
    """P_a^alt: graph on [a], edges = consecutive pairs of the sequence
    (0, a-1, 1, a-2, 2, a-3, ...). Returns a frozenset of frozenset pairs."""
    assert a >= 2
    seq = []
    for t in range((a + 1) // 2):
        seq.append(t)
        if len(seq) < a:
            seq.append(a - 1 - t)
    seq = seq[:a]
    edges = set()
    for i in range(a - 1):
        edges.add(frozenset((seq[i], seq[i + 1])))
    assert len(edges) == a - 1, (a, seq, edges)
    return frozenset(edges)


def dihedral_group(m):
    """Dih(m) <= Sym([m]) generated by rho(i)=i+1 mod m, sigma(i)=m-1-i.
    Returns the set of group elements as tuples (perm[0..m-1])."""
    def rho(p):
        return tuple((x + 1) % m for x in range(m))  # rho itself as a perm array: rho[i]=i+1 mod m
    def compose(p, q):
        # (p o q)(i) = p(q(i))
        return tuple(p[q[i]] for i in range(m))

    rho_perm = tuple((i + 1) % m for i in range(m))
    sigma_perm = tuple((m - 1 - i) % m for i in range(m))
    identity = tuple(range(m))

    group = {identity}
    frontier = [identity]
    gens = [rho_perm, sigma_perm]
    while frontier:
        new_frontier = []
        for g in frontier:
            for gen in gens:
                h = compose(gen, g)
                if h not in group:
                    group.add(h)
                    new_frontier.append(h)
        frontier = new_frontier
    return group


def apply_perm_to_edges(perm, edges):
    """gamma(H): edge set {{gamma(i),gamma(j)} : {i,j} in E(H)}."""
    return frozenset(frozenset((perm[i], perm[j])) for e in edges for (i, j) in [tuple(e)])


def is_increasing(v):
    return all(v[i] < v[i + 1] for i in range(len(v) - 1))


def has_gamma_copy(H_edges, m, Gamma, n, color_pairs_have_color_r):
    """Does there exist an increasing v:[m]->[n] and gamma in Gamma such that
    every edge {i,j} of H_edges maps to a pair {v[gamma(i)],v[gamma(j)]}
    with color r (per color_pairs_have_color_r(x,y)->bool)?
    This is the literal statement.md Gamma-copy definition -- brute force
    over increasing tuples and group elements."""
    for gamma in Gamma:
        # Precompute the edge-index-pairs to check: for each edge {i,j} of H,
        # need pair {v[gamma(i)], v[gamma(j)]}.
        gi_pairs = [tuple(sorted((gamma[i], gamma[j]))) for e in H_edges for (i, j) in [tuple(e)]]
        for v in combinations(range(n), m):
            if all(color_pairs_have_color_r(v[p], v[q]) for (p, q) in gi_pairs):
                return True, v, gamma
    return False, None, None


def orbit_of_graph(edges, m, Gamma):
    """{gamma(H): gamma in Gamma} as a set of frozensets."""
    return {apply_perm_to_edges(g, edges) for g in Gamma}


def stabilizer_size(edges, m, Gamma):
    return sum(1 for g in Gamma if apply_perm_to_edges(g, edges) == edges)


def all_colorings(n):
    """Yield every 2-coloring of K_n as a dict {(i,j): color} for i<j,
    color in {1,2}. Represented compactly as a bitmask over the C(n,2)
    edges (bit=1 -> color 2, bit=0 -> color 1) plus the edge list."""
    edge_list = list(combinations(range(n), 2))
    E = len(edge_list)
    for mask in range(1 << E):
        yield edge_list, mask


def mask_color(edge_list, mask, i, j):
    idx = edge_list.index((i, j) if i < j else (j, i))
    return 2 if (mask >> idx) & 1 else 1
